-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isTwoFaActive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "secret" TEXT NOT NULL DEFAULT E'';
